### ISSUE TITLE
リクエストのContent-Typeが変更できない

### ISSUE THREAD

**Issue by Kiikurage** [HakabaV3/izu-server#16]
## 症状
1. `Access-Control-Allow-Headers` に `Content-Type` が無いので外からヘッダを書き換えられない
2. expressのjsonParserは `Content-Type: application/json` が無いとパースしてくれない
3. リクエストが皆 `INVALID_PARAMETERS` になる
## 対処法

`Access-Control-Allow-Headers` に `Content-Type` を追加する

**Comment by Dooor** [comment]
DONE
