### ISSUE TITLE
プランのIDが重複して作成されてしまう

### ISSUE THREAD

**Issue by Kiikurage** [HakabaV3/izu-server#20]
`GET /plan` のレスポンス

![2015-12-12 14 18 06](https://cloud.githubusercontent.com/assets/3253117/11760360/3a4c80a4-a0db-11e5-8e0f-844ad1e88886.png)

**Comment by Kiikurage** [comment]
https://github.com/HakabaV3/izu-server/blob/master/schema/plan.js#L29-L32

これ、uuidを個別に設定しなかったらデフォルト値が使いまわされてしまうのでは。

**Comment by Dooor** [comment]
まじかい

**Comment by Dooor** [comment]
CLOSE
